set nocompatible
set autoindent
set background=dark
set cursorline
set expandtab
set ignorecase
set incsearch
set laststatus=2 " needed for airline
set mouse=a
set nohlsearch
set noshowmode " airline already shows me
set number
set ruler
set smartcase
set smartindent
set smarttab
set shiftwidth=4
set showcmd
set showmatch
set softtabstop=4
set tabstop=4
syntax on

filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" extensions
Plugin 'gmarik/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/syntastic'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'

" colorschemes
Plugin 'sjl/badwolf'
Plugin 'tomasr/molokai'
call vundle#end()

filetype plugin indent on

map <silent> <C-i> gg=G'
map <C-e> :NERDTreeToggle<cr>

map <C-t> :tabnew<cr>
map <C-o> :tabedit 
map <C-w> :tabclose<cr>
map <C-a> :tabprevious<cr>
map <C-d> :tabnext<cr>

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:badwolf_css_props_highlight = 1
let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 0

set shell=/bin/sh
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_compiler_options = '-Wall -Wpedantic -std=c++14'

colorscheme badwolf
highlight NonText ctermbg=none
highlight Normal ctermbg=none
