set nocompatible
set autoindent
set background=dark
set cursorline
"set expandtab
set ignorecase
set incsearch
set laststatus=2 " eeded for airline
set mouse=a
set nohlsearch
set noshowmode " irline already shows me
set number
set ruler
set smartcase
set smartindent
set smarttab
set shiftwidth=2
set showcmd
set showmatch
set softtabstop=2
set tabstop=2
syntax on

filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" extensions
Plugin 'gmarik/Vundle.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/syntastic'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'

" colorschemes
Plugin 'sjl/badwolf'
Plugin 'tomasr/molokai'
call vundle#end()

filetype plugin indent on

colorscheme molokai
