" General
set number	" Show line numbers
set relativenumber
set showbreak=+++ 	" Wrap-broken line prefix
set showmatch	" Highlight matching brace
set noshowmode
 
set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally
 
set autoindent	" Auto-indent new lines
set shiftwidth=2	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=2	" Number of spaces per Tab
 
" Advanced
set ruler	" Show row and column ruler information

set autochdir	" Change working directory to open buffer
 
set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Enable filetype plugins
syntax on

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","

" Theme
packadd nord
colorscheme nord
hi Normal guibg=NONE ctermbg=NONE
hi NonText ctermbg=NONE guibg=NONE
hi IndentGuidesEven ctermbg=black
hi IndentGuidesOdd ctermbg=black

let g:indent_guides_auto_colors = 0
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1

" Shortcuts
" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Turn off arrows
noremap <silent> <Left> <NOP>
noremap <silent> <Down> <NOP>
noremap <silent> <Up> <NOP>
noremap <silent> <Right> <NOP>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Treat long lines as break lines (useful when moving around in them)
map j gj
map k gk

" Keep selection when moving code blocks
vnoremap < <gv
vnoremap > >gv

" Open file browser
map <Leader>e :NERDTreeToggle<CR>

" Extensions

" CtrlP
let g:ctrlp_map = '<leader>p'
