"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false
right_format = """$time"""

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[package]
disabled = true

[status]
disabled = false

[time]
format = "[$time]($style)"
time_format = "%R"
disabled = false

[line_break]
disabled = true
