# Don't print a new line at the start of the prompt
add_newline = false

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[package]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[line_break]
disabled = true
