# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

right_format = """$time"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[package]
disabled = true

[status]
disabled = false

[time]
format = "[$time]($style)"
time_format = "%R"
disabled = false
