if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge ~/.Xresources &
xset dpms 0 0 600 &
xautolock -time 10 -locker i3lock-wrapper &
xcompmgr -c -D4 -f -F -o0.8 -r10 &
oneko -tora &

exec i3
